services:
  server:
    image: node:22-alpine3.18
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run start:dev

  postgres:
    image: postgres:17-alpine3.21
    ports:
      - "5432:5432"
    env_file:
      - .env